### ISSUE TITLE
First event to the right of container again

### ISSUE THREAD

**Issue by scioffi** [rit-sse/events#26] opened 2017-01-24 23:25 UTC
![image](https://cloud.githubusercontent.com/assets/2954285/22271416/7447d6b8-e262-11e6-868c-15dcb9417df5.png)

**Comment by billdybas** [comment] 2017-01-24 23:40
This is a regression from what was fixed in #16 since those changed were merged into broken branch and then reverted. I've made another PR (#27) which should fix this.

**Closed as completed** 2017-01-25 01:47 UTC
