### ISSUE TITLE
Title too long error message

### ISSUE THREAD

**Issue by djrenren** [rit-sse/events#6] opened 2016-01-19 19:39 UTC
When the title is too long, it should say so instead of "Unprocessable Entity"

**Comment by kristenmills** [comment] 2016-01-19 20:06
Closed as duplicate of #1

**Closed as completed by kristenmills** 2016-01-19 20:06 UTC

**Comment by djrenren** [comment] 2016-01-22 23:22
Why not just reference the task from the parent task? Or at least update the other task with a list of required error messages.

Otherwise we could close all tasks as dups of a "Make it good" task.

**Comment by kristenmills** [comment] 2016-01-23 00:08
Sorry, I should have explained my reasoning for closing this better. 

This is to granular and a symptom of a bigger problem. The actual task I care about is display validation messages instead of "Unprocessable Entity". I don't care on any level what the validation messages are as far as events is concerned. And if I don't care in this context, I don't need an issue for it.
